// Generated by accept-md. Do not edit the markdown block by hand.
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { getMarkdownForPath, loadConfig } from 'accept-md-runtime';

const cache = new Map();
const HANDLER_PATH = '/api/accept-md';

export async function GET(request: NextRequest) {
  const pathFromHeader = request.headers.get('x-accept-md-path');
  const pathFromQuery = request.nextUrl.searchParams.get('path');
  const pathname = request.nextUrl.pathname;
  const path = pathFromHeader ?? pathFromQuery ?? (pathname !== HANDLER_PATH ? pathname : null) ?? '/';
  const config = loadConfig(process.cwd());
  const baseUrl = config.baseUrl || request.nextUrl.origin;
  try {
    const markdown = await getMarkdownForPath({
      pathname: path,
      baseUrl,
      config,
      cache: config.cache !== false ? cache : undefined,
      headers: request.headers,
    });
    return new NextResponse(markdown, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Cache-Control': config.cache ? 'public, s-maxage=60, stale-while-revalidate' : 'no-store',
      },
    });
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Markdown generation failed' },
      { status: 500 }
    );
  }
}
