// Generated by accept-md. Do not edit the markdown block by hand.
import { NextResponse } from 'next/server';

const MARKDOWN_ACCEPT = new RegExp('\\btext/markdown\\b', 'i');
const EXCLUDED_PREFIXES = ['/api/', '/_next/'];
const MARKDOWN_HANDLER_PATH = '/api/accept-md';

/** @param {import('next/server').NextRequest} request */
export function middleware(request) {
  const pathname = request.nextUrl.pathname;
  const accept = (request.headers.get('accept') || '').toLowerCase();
  if (!MARKDOWN_ACCEPT.test(accept)) return NextResponse.next();
  if (EXCLUDED_PREFIXES.some((p) => pathname.startsWith(p))) return NextResponse.next();

  const url = request.nextUrl.clone();
  url.pathname = MARKDOWN_HANDLER_PATH;
  url.searchParams.set('path', pathname);
  // Let Next.js carry through original headers/cookies; only use query param for the path.
  return NextResponse.rewrite(url);
}
