// SvelteKit example handler for accept-md.
// In real projects this file is generated by `npx accept-md init`.
import { getMarkdownForPath, loadConfig } from 'accept-md-runtime';

const cache = new Map();
const HANDLER_PATH = '/api/accept-md';

export async function GET(event) {
  const url = event.url;
  const request = event.request;

  const pathFromHeader = request.headers.get('x-accept-md-path');
  const pathFromQuery = url.searchParams.get('path');
  const pathname = url.pathname;

  let path = pathFromHeader && pathFromHeader.trim() !== '' ? pathFromHeader : null;
  if (!path && pathFromQuery && pathFromQuery.trim() !== '') {
    path = pathFromQuery;
  }
  if (!path && pathname.startsWith(HANDLER_PATH + '/')) {
    path = pathname.slice(HANDLER_PATH.length);
    if (path === '') {
      path = '/';
    }
  }
  if (!path || path === HANDLER_PATH) {
    path = '/';
  }
  if (!path.startsWith('/')) {
    path = '/' + path;
  }

  if (path.startsWith('/api/') || path.startsWith('/_next/')) {
    return new Response(JSON.stringify({ error: 'Not found' }), {
      status: 404,
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
      },
    });
  }

  const config = loadConfig(process.cwd());

  let baseUrl = config.baseUrl;
  if (!baseUrl) {
    baseUrl = url.origin || 'http://localhost:' + (process.env.PORT || 5173);
  }

  const headers = new Headers(request.headers);
  headers.delete('accept');

  try {
    const markdown = await getMarkdownForPath({
      pathname: path,
      baseUrl,
      config,
      cache: config.cache !== false ? cache : undefined,
      headers,
    });
    return new Response(markdown, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Cache-Control': config.cache ? 'public, s-maxage=60, stale-while-revalidate' : 'no-store',
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Markdown generation failed';
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: {
        'Content-Type': 'application/json; charset=utf-8',
      },
    });
  }
}

